### ISSUE TITLE
Some doubts

### ISSUE THREAD

**Issue by GWan1234** [jonkofee/esp8266-homekit-socket#1]
Thank you for sharing, I have compiled the device, but after writing the firmware,
 I can‘t search for the device. I used the Windows software to write the firmware. 
What is the port number for writing, I used 0x00000, but it seems to be incorrect, 
in short The device cannot be scanned. I need your help.

**Comment by jonkofee** [comment]
Hi. I'm use Mac OS, so I don't known how to compile in Windows. Use Linux
